Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,6 +24,21 @@ jobs:
         run: |
           cat report.xml
 
+      - shell: bash
+        run: |
+          set -x
+
+          # Check if FILES and MERGIFY_CI_ISSUES_TOKEN are set and not empty
+          if [ -z "$FILES" ]; then
+            echo "Error: FILES is not set or is empty"
+            exit 1
+          fi
+      
+          if [ -z "$MERGIFY_CI_ISSUES_TOKEN" ]; then
+            echo "Error: MERGIFY_CI_ISSUES_TOKEN is not set or is empty"
+            exit 1
+          fi
+
       - name: Mergify JUnit XML Upload
         if: always()
         uses: mergifyio/gha-ci-issues@v1
